##############################################
# CONFIGURATION FILE FOR FINE TUNING PROCESS #
##############################################

###################
# model selection #
###################

model:
    checkpoints: "/home/divit/projects/models/dinov2.2CrossAttn.CMU.pth"              # path to the pre-trained model
    target-shp-row: 504
    target-shp-col: 504          # 224 for PSCD

#############
# optimizer #
#############

# ---------
optimizer:
    epochs: 25
    warmup-epoch: 0
    learn-rate: 0.00004
    loss-weight: True
    lr-scheduler: "none"    # {cosine, linear, exp, none}
    grad-scaler: True       # enable mixed precision

###########
# dataset #
###########

# -------
dataset:
    batch-size: 2
    num-workers: 4
    dataset: "YOUR_CUSTOM"         # PSCD
    hflip-prob: 0.5

##############
# evaluation #
##############

# ----------
evaluation:
    # name: epoch frequency
    trainset: 0

#########
# wandb #
#########

# ------
wandb:
    project: ""
    name: ""
    output-path: ""
    save-checkpoint-freq: 0  # frequency

########################
# develope and testing #
########################

# --------------------
environment:
    dry: False
    seed: 123
    verbose: True
    device: "cuda"